// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708223756_AddBonusFieldsAndSeeding")]
    partial class AddBonusFieldsAndSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CargoValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FloorPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("FuelConsumptionRate")
                        .HasColumnType("float");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoImageUrl = "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 80000m,
                            Description = "2+1 ev eşyası taşınacaktır. Dikkatli ve özenli taşıma gereklidir.",
                            DistanceKm = 480.0,
                            EndLocation = "İstanbul",
                            FloorPrice = 3360m,
                            FuelConsumptionRate = 12.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "İzmir",
                            Status = "Active",
                            Title = "İzmir - İstanbul Ev Eşyası Taşıma",
                            VerificationCode = "LY-1209"
                        },
                        new
                        {
                            Id = 2,
                            CargoImageUrl = "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 200000m,
                            Description = "15 ton paletli demir boru sevkiyatı. Dorseli tır gereklidir.",
                            DistanceKm = 350.0,
                            EndLocation = "Ankara",
                            FloorPrice = 6240m,
                            FuelConsumptionRate = 32.0,
                            RequiredLevel = 2,
                            SenderId = 1,
                            StartLocation = "Kocaeli",
                            Status = "Active",
                            Title = "Kocaeli - Ankara Paletli Demir Boru",
                            VerificationCode = "LY-8549"
                        },
                        new
                        {
                            Id = 3,
                            CargoImageUrl = "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 500000m,
                            Description = "Yüksek riskli kimyasal madde taşıması. ADR belgeli araç ve özel sigorta zorunludur.",
                            DistanceKm = 420.0,
                            EndLocation = "Batman",
                            FloorPrice = 8115m,
                            FuelConsumptionRate = 35.0,
                            RequiredLevel = 3,
                            SenderId = 1,
                            StartLocation = "İskenderun",
                            Status = "Active",
                            Title = "İskenderun - Batman Kimyasal Hammadde",
                            VerificationCode = "LY-4281"
                        },
                        new
                        {
                            Id = 101,
                            CargoImageUrl = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 60000m,
                            Description = "İzmir'e geri dönecek araçlar için mobilya yükü.",
                            DistanceKm = 480.0,
                            EndLocation = "İzmir",
                            FloorPrice = 3200m,
                            FuelConsumptionRate = 12.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "İstanbul",
                            Status = "Active",
                            Title = "İstanbul - İzmir Dönüş Sevkiyatı",
                            VerificationCode = "LY-4091"
                        },
                        new
                        {
                            Id = 102,
                            CargoImageUrl = "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 120000m,
                            Description = "Kocaeli yönüne dönecek tırlar için paletli rulo sac.",
                            DistanceKm = 350.0,
                            EndLocation = "Kocaeli",
                            FloorPrice = 5800m,
                            FuelConsumptionRate = 30.0,
                            RequiredLevel = 2,
                            SenderId = 1,
                            StartLocation = "Ankara",
                            Status = "Active",
                            Title = "Ankara - Kocaeli Paletli Yük",
                            VerificationCode = "LY-5120"
                        },
                        new
                        {
                            Id = 103,
                            CargoImageUrl = "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 400000m,
                            Description = "Liman yönüne dönecek tanker veya dorseler için ham petrol türevi.",
                            DistanceKm = 420.0,
                            EndLocation = "İskenderun",
                            FloorPrice = 7900m,
                            FuelConsumptionRate = 35.0,
                            RequiredLevel = 3,
                            SenderId = 1,
                            StartLocation = "Batman",
                            Status = "Active",
                            Title = "Batman - İskenderun Boş Dönüş Yükü",
                            VerificationCode = "LY-6031"
                        },
                        new
                        {
                            Id = 104,
                            CargoImageUrl = "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 150000m,
                            Description = "Soğutmalı kasa (frigo) van veya kamyon için gıda paletleri.",
                            DistanceKm = 450.0,
                            EndLocation = "Ankara",
                            FloorPrice = 4200m,
                            FuelConsumptionRate = 20.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "İstanbul",
                            Status = "Active",
                            Title = "İstanbul - Ankara Acil Gıda Sevkiyatı",
                            VerificationCode = "LY-7102"
                        },
                        new
                        {
                            Id = 105,
                            CargoImageUrl = "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 170000m,
                            Description = "İstanbul'a dönecek araçlar için hafif ama hacimli ambalaj kutuları.",
                            DistanceKm = 450.0,
                            EndLocation = "İstanbul",
                            FloorPrice = 4400m,
                            FuelConsumptionRate = 20.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "Ankara",
                            Status = "Active",
                            Title = "Ankara - İstanbul Ambalaj Malzemesi",
                            VerificationCode = "LY-8192"
                        },
                        new
                        {
                            Id = 106,
                            CargoImageUrl = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 50000m,
                            Description = "İzmir yönüne boş dönecek van veya kamyonet için paletsiz koliler.",
                            DistanceKm = 330.0,
                            EndLocation = "İzmir",
                            FloorPrice = 2800m,
                            FuelConsumptionRate = 15.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "Bursa",
                            Status = "Active",
                            Title = "Bursa - İzmir Parça Koli Taşıma",
                            VerificationCode = "LY-9104"
                        },
                        new
                        {
                            Id = 107,
                            CargoImageUrl = "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 90000m,
                            Description = "Bursa tekstil bölgesine gidecek iplik çuvalları.",
                            DistanceKm = 330.0,
                            EndLocation = "Bursa",
                            FloorPrice = 3000m,
                            FuelConsumptionRate = 15.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "İzmir",
                            Status = "Active",
                            Title = "İzmir - Bursa Tekstil Hammaddesi",
                            VerificationCode = "LY-1094"
                        },
                        new
                        {
                            Id = 108,
                            CargoImageUrl = "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&w=600&q=80",
                            CargoValue = 130000m,
                            Description = "Bursa fabrikasına acil yedek parça teslimatı.",
                            DistanceKm = 150.0,
                            EndLocation = "Bursa",
                            FloorPrice = 2200m,
                            FuelConsumptionRate = 20.0,
                            RequiredLevel = 2,
                            SenderId = 1,
                            StartLocation = "İstanbul",
                            Status = "Active",
                            Title = "İstanbul - Bursa Otomotiv Yedek Parça",
                            VerificationCode = "LY-1102"
                        });
                });

            modelBuilder.Entity("backend.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("CarrierId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("backend.Models.CarrierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InsuranceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CarrierProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsuranceNo = "",
                            LicenseType = "B Sınıfı",
                            Rating = 4.2000000000000002,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            InsuranceNo = "",
                            LicenseType = "C Sınıfı",
                            Rating = 4.7000000000000002,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            InsuranceNo = "POL-9876543-XYZ",
                            LicenseType = "CE (Ağır Vasıta)",
                            Rating = 4.9000000000000004,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountBlockedCarrier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountBlockedSender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerifiedByAi")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PeriodicBonusActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WelcomeBonusExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 150000m,
                            Email = "ahmet@lojistikyol.com",
                            Name = "Ahmet (Gönderici)",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            PeriodicBonusActive = false,
                            UserLevel = 1,
                            UserType = "Sender"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 20000m,
                            Email = "mehmet@lojistikyol.com",
                            Name = "Mehmet (Lvl 1 Taşıyıcı)",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            PeriodicBonusActive = true,
                            UserLevel = 1,
                            UserType = "Carrier",
                            WelcomeBonusExpiry = new DateTime(2026, 7, 15, 15, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Balance = 25000m,
                            Email = "ali@lojistikyol.com",
                            Name = "Ali (Lvl 2 Taşıyıcı)",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            PeriodicBonusActive = true,
                            UserLevel = 2,
                            UserType = "Carrier"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 5000m,
                            Email = "veli@lojistikyol.com",
                            Name = "Veli (Lvl 3 Taşıyıcı)",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            PeriodicBonusActive = false,
                            UserLevel = 3,
                            UserType = "Carrier"
                        });
                });

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.HasOne("backend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("backend.Models.Bid", b =>
                {
                    b.HasOne("backend.Models.Ad", "Ad")
                        .WithMany("Bids")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("backend.Models.CarrierProfile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("CarrierProfile")
                        .HasForeignKey("backend.Models.CarrierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.HasOne("backend.Models.Bid", "Bid")
                        .WithOne()
                        .HasForeignKey("backend.Models.Transaction", "BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("CarrierProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
