// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609034540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CargoValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FloorPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("FuelConsumptionRate")
                        .HasColumnType("float");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoValue = 80000m,
                            Description = "2+1 ev eşyası taşınacaktır. Dikkatli ve özenli taşıma gereklidir.",
                            DistanceKm = 480.0,
                            EndLocation = "İstanbul",
                            FloorPrice = 3360m,
                            FuelConsumptionRate = 12.0,
                            RequiredLevel = 1,
                            SenderId = 1,
                            StartLocation = "İzmir",
                            Status = "Active",
                            Title = "İzmir - İstanbul Ev Eşyası Taşıma"
                        },
                        new
                        {
                            Id = 2,
                            CargoValue = 200000m,
                            Description = "15 ton paletli demir boru sevkiyatı. Dorseli tır gereklidir.",
                            DistanceKm = 350.0,
                            EndLocation = "Ankara",
                            FloorPrice = 6240m,
                            FuelConsumptionRate = 32.0,
                            RequiredLevel = 2,
                            SenderId = 1,
                            StartLocation = "Kocaeli",
                            Status = "Active",
                            Title = "Kocaeli - Ankara Paletli Demir Boru"
                        },
                        new
                        {
                            Id = 3,
                            CargoValue = 500000m,
                            Description = "Yüksek riskli kimyasal madde taşıması. ADR belgeli araç ve özel sigorta zorunludur.",
                            DistanceKm = 420.0,
                            EndLocation = "Batman",
                            FloorPrice = 8115m,
                            FuelConsumptionRate = 35.0,
                            RequiredLevel = 3,
                            SenderId = 1,
                            StartLocation = "İskenderun",
                            Status = "Active",
                            Title = "İskenderun - Batman Kimyasal Hammadde"
                        });
                });

            modelBuilder.Entity("backend.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("CarrierId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("backend.Models.CarrierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InsuranceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CarrierProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsuranceNo = "",
                            LicenseType = "B Sınıfı",
                            Rating = 4.2000000000000002,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            InsuranceNo = "",
                            LicenseType = "C Sınıfı",
                            Rating = 4.7000000000000002,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            InsuranceNo = "POL-9876543-XYZ",
                            LicenseType = "CE (Ağır Vasıta)",
                            Rating = 4.9000000000000004,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountBlockedCarrier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountBlockedSender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BidId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 150000m,
                            Name = "Ahmet (Gönderici)",
                            UserLevel = 1,
                            UserType = "Sender"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 20000m,
                            Name = "Mehmet (Lvl 1 Taşıyıcı)",
                            UserLevel = 1,
                            UserType = "Carrier"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 25000m,
                            Name = "Ali (Lvl 2 Taşıyıcı)",
                            UserLevel = 2,
                            UserType = "Carrier"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 5000m,
                            Name = "Veli (Lvl 3 Taşıyıcı)",
                            UserLevel = 3,
                            UserType = "Carrier"
                        });
                });

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.HasOne("backend.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("backend.Models.Bid", b =>
                {
                    b.HasOne("backend.Models.Ad", "Ad")
                        .WithMany("Bids")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("backend.Models.CarrierProfile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("CarrierProfile")
                        .HasForeignKey("backend.Models.CarrierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Transaction", b =>
                {
                    b.HasOne("backend.Models.Bid", "Bid")
                        .WithOne()
                        .HasForeignKey("backend.Models.Transaction", "BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("backend.Models.Ad", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("CarrierProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
